#!/usr/bin/env node
/**
 * End-to-end depth parity: run the real app inference route on the reference
 * image and compare the final depth map against the PyTorch reference
 * (public/layer_dumps/depth_final.bin, generated by dump_layer_outputs.py from
 * the same checkpoint the app ships: Ruicheng/moge-2-vitl-normal).
 *
 * The app produces depth at its native 592x592 processing resolution; the
 * reference is 518x518. The app output is bilinearly resampled to 518x518
 * before comparison.
 *
 * Metrics (all over finite pixels):
 *   - relAbsMean / relAbsMedian: |gpu - ref| / ref
 *   - logRms: RMS of log(gpu/ref) (scale-aware)
 *   - scaleMedian: median(gpu/ref) — global metric-scale agreement
 *   - alignedRelRms: rel RMS after dividing out scaleMedian (scale-invariant)
 *
 * Usage: node tools/test_depth_parity.mjs [--port 5182] [--headed]
 * Exit code 1 if the comparison could not run or alignedRelRms > 0.005.
 */

import puppeteer from 'puppeteer-core';
import path from 'path';
import { fileURLToPath } from 'url';

const CHROME_PATH = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
  const args = process.argv.slice(2);
  const port = args.includes('--port') ? args[args.indexOf('--port') + 1] : '5182';
  const headed = args.includes('--headed');
  const url = `http://localhost:${port}/`;

  console.log(`Depth parity — ${url}\n`);

  const browser = await puppeteer.launch({
    executablePath: CHROME_PATH,
    headless: !headed,
    args: [
      '--enable-unsafe-webgpu',
      '--enable-features=Vulkan',
      '--disable-gpu-sandbox',
      '--no-sandbox',
      '--disable-gpu-shader-disk-cache',
    ],
    defaultViewport: { width: 1280, height: 900 },
  });

  const page = await browser.newPage();
  page.on('console', msg => {
    const t = msg.text();
    if (/Loaded|weights|Error|error/.test(t)) console.log(`  [page] ${t}`);
  });

  try {
    await page.goto(url, { waitUntil: 'networkidle0', timeout: 60000 });

    const testImagePath = path.resolve(__dirname, '..', 'public', 'test_fixtures', 'input.png');
    const fileInput = await page.$('#file-input');
    await fileInput.uploadFile(testImagePath);

    await page.waitForFunction(
      () => document.getElementById('output')?.classList.contains('visible') && window.__mogeResult,
      { timeout: 300000 }
    );

    const metrics = await page.evaluate(async () => {
      // Route authority: refuse to compare anything but the real-weights route.
      // (Stub-weight fallback produces plausible-looking garbage metrics.)
      if (!window.__mogeInference?.useRealWeights) {
        return { error: 'inference ran on stub weights — no authoritative comparison possible' };
      }
      const result = window.__mogeResult;
      const gw = result.width, gh = result.height;
      const gpu = result.depth;

      const resp = await fetch('/layer_dumps/depth_final.bin');
      if (!resp.ok) return { error: `depth_final.bin fetch: ${resp.status}` };
      const ref = new Float32Array(await resp.arrayBuffer());
      const rs = Math.round(Math.sqrt(ref.length)); // 518
      if (rs * rs !== ref.length) return { error: `ref not square: ${ref.length}` };

      // Bilinear sample GPU depth at each ref pixel center
      const sample = (x, y) => {
        const x0 = Math.floor(x), y0 = Math.floor(y);
        const x1 = Math.min(x0 + 1, gw - 1), y1 = Math.min(y0 + 1, gh - 1);
        const fx = x - x0, fy = y - y0;
        const v00 = gpu[y0 * gw + x0], v10 = gpu[y0 * gw + x1];
        const v01 = gpu[y1 * gw + x0], v11 = gpu[y1 * gw + x1];
        return (v00 * (1 - fx) + v10 * fx) * (1 - fy) + (v01 * (1 - fx) + v11 * fx) * fy;
      };

      const relErrs = [], ratios = [], logDiffs = [];
      for (let ry = 0; ry < rs; ry++) {
        for (let rx = 0; rx < rs; rx++) {
          const r = ref[ry * rs + rx];
          const g = sample(((rx + 0.5) / rs) * gw - 0.5, ((ry + 0.5) / rs) * gh - 0.5);
          if (!isFinite(r) || !isFinite(g) || r <= 0 || g <= 0) continue;
          relErrs.push(Math.abs(g - r) / r);
          ratios.push(g / r);
          logDiffs.push(Math.log(g / r));
        }
      }
      if (!relErrs.length) return { error: 'no finite overlapping pixels' };

      const median = a => { const s = [...a].sort((x, y) => x - y); return s[s.length >> 1]; };
      const mean = a => a.reduce((s, v) => s + v, 0) / a.length;
      const scaleMedian = median(ratios);
      const alignedSq = ratios.map(q => (q / scaleMedian - 1) ** 2);

      return {
        pixels: relErrs.length,
        gpuSize: `${gw}x${gh}`,
        refSize: `${rs}x${rs}`,
        relAbsMean: mean(relErrs),
        relAbsMedian: median(relErrs),
        logRms: Math.sqrt(mean(logDiffs.map(d => d * d))),
        scaleMedian,
        alignedRelRms: Math.sqrt(mean(alignedSq)),
        weightsSource: window.__mogeInference?.weightsSource || 'unknown',
      };
    });

    console.log(JSON.stringify(metrics, null, 2));
    if (metrics.error) process.exitCode = 1;
    else if (metrics.alignedRelRms > 0.005) {
      console.log(`\nFAIL: alignedRelRms ${metrics.alignedRelRms.toFixed(4)} > 0.005`);
      process.exitCode = 1;
    } else {
      console.log('\nPASS');
    }
  } catch (e) {
    console.error('ERROR:', e.message);
    process.exitCode = 1;
  } finally {
    await browser.close();
  }
}

main();
